server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://dpg-d8r7ngojs32c73bneg60-a.oregon-postgres.render.com:5432/ecommerce_db_csre
spring.datasource.username=ecommerce_db_csre_user
spring.datasource.password=6FKAWm8EBAbaHBcuN0y2I0RljaGdx41B

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
